### ISSUE TITLE
Downloads doesn't work for some links

### ISSUE THREAD

**Issue by Adam-Orzechowski** [gnojus/wedl#10]
Unfortunately, in some cases download is not saved on disk. We used this software for a long time and this started today. 04.10.2024. Not all download links are broken, only some.

**Comment by wippart** [comment]
error is:  Unable to get direct link: No download access to this Transfer
What I found out for another solution(node.js with puppeteer) - wetransfer changed cookie consent behavoiur (buttons renamed)

**Comment by gnojus** [comment]
Hi,

thanks for the report. I pushed a new version (v0.1.10), let me know if it fixes the issue.

**Comment by wippart** [comment]
Hey,
it works, thank you very much.

Have a nice day

Wipp



Frank Wipperfuerth Er/ihm
Digital Process Optimization
Telefon: +49 (0)172 2949523
Wigeystraße 18 – 20
​57368 Lennestadt, Deutschland
Mossinc.de
Geschäftsführer: Peter Bottenberg, Jason Fieber 
UST-ID-Nr.: DE 126 177 684 | Steuer-Nr.: 338/5855/0711 
​Registergericht Siegen HRB 5925

Hinweis zum Datenschutz:
Diese E-Mail enthält vertrauliche oder rechtlich geschützte Informationen. 
​Wenn Sie nicht der richtige Adressat sind oder
diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort 
​den Absender oder vernichten Sie diese E-Mail.
Das unerlaubte Kopieren und die unbefugte Weitergabe 
​dieser E-Mail sind nicht gestattet.
Von: Nojus Gudinavičius ***@***.***>
Gesendet: Samstag, 5. Oktober 2024 17:54
An: gnojus/wedl ***@***.***>
Cc: Frank Wipperfuerth ***@***.***>; Comment ***@***.***>
Betreff: Re: [EXTERNAL] [gnojus/wedl] Downloads doesn't work for some links (Issue #10)


Hi,

thanks for the report. I pushed a new version (v0.1.10), let me know if it fixes the issue.

**Comment by wippart** [comment]
works again.. thanks a lot
