### ISSUE TITLE
Does not download files

### ISSUE THREAD

**Issue by enten64** [gnojus/wedl#6]
Hello,
	
today I noticed this error message:

An attempt was made to access a socket in a way forbidden by its access permissions.

v0.1.6, wedl-windows-amd64.exe

**Comment by gnojus** [comment]
That's a weird error, maybe windows related?
Anyway, noticed that csrf token was preventing download for me as well, should be fixed with 0.1.8

**Comment by enten64** [comment]
Well, v0.1.8 is working fine :) Thank you
